version: '3'
services:
  quiz-api:
    build: .
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    environment:
      - NODE_ENV=development
    networks:
      - quiz-net

networks:
  quiz-net:
    driver: bridge
